on:
  push:
    branches:
      - main
      - pkgdown
  pull_request:
    branches:
      - main
      - pkgdown
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSC_VERSION: 2022.09.0
      RSC_LICENSE: ${{ secrets.RSC_LICENSE }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Install dependencies
        # TODO: a way to do this using setup-r-dependencies action...?
        run: |
          # TODO: dev version for pkg_lifecycle_statuses function
          remotes::install_github("r-lib/lifecycle")
        shell: Rscript {0}

      - name: Start Connect
        run: |
          Rscript -e 'connectapi:::build_test_env()'

      - name: Deploy package
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'

      - name: Build site without deploying
        if: github.event_name == 'pull_request'
        run: |
          Rscript -e 'pkgdown::build_site(preview = FALSE, install = FALSE)'
